[project]
name = "lynkscan"
description = "Scan licenses and vulnerabilities of open source softwares."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-ollama",
    "sqlmodel",
    "beautifulsoup4",
]
dynamic = ["version"]

[project.scripts]
init-database = "lynkscan.cli:run_init_database"
fetch-license-info = "lynkscan.cli:run_fetch_license_info"
register-software-categories = "lynkscan.cli:run_register_software_categories"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.hooks.version]
path = "src/lynkscan/_version.py"
template = '''
version = "{version}"
'''

[tool.isort]
force_single_line = true

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["D", "E", "F", "C90", "I"]
fixable = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["lynkscan"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
force-single-line = true
combine-as-imports = true
from-first = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
preview = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
testpaths = ["tests"]
